// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsP62XX8d1Mla42mST3br12K__uiy0nyI',
    appId: '1:901723470459:web:5e732638f02e2451fbc0de',
    messagingSenderId: '901723470459',
    projectId: 'flutteraljid',
    authDomain: 'flutteraljid.firebaseapp.com',
    storageBucket: 'flutteraljid.appspot.com',
    measurementId: 'G-8VJZEWZ13F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9lobxf_M1emSH4n4DhnIvldQUWSkErXA',
    appId: '1:901723470459:android:5441bf349de1a84efbc0de',
    messagingSenderId: '901723470459',
    projectId: 'flutteraljid',
    storageBucket: 'flutteraljid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClXjCoHUKNWUjwbJPy8NejpAzboO6Ze-8',
    appId: '1:901723470459:ios:881a333a3c8ce534fbc0de',
    messagingSenderId: '901723470459',
    projectId: 'flutteraljid',
    storageBucket: 'flutteraljid.appspot.com',
    androidClientId: '901723470459-dpu5i69u5pkd8b3vq6h0ldes1eat63ur.apps.googleusercontent.com',
    iosClientId: '901723470459-hve0iljslrd1j55l8o6sghhuv66g5fgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.aljid',
  );
}
